allow_origins:
  - "https://example.com"
allow_methods:
  - "GET"
  - "POST"
  - "DELETE"
  - "OPTIONS"
  - "PUT"
  - "PATCH"
allow_headers:
  - "Origin"
expose_headers:
  - "Content-Length"
allow_credentials: true
allow_origin_func:
  - "https://example.com"
max_age: 3600 
